# Generated by Django 5.0.1 on 2024-01-18 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, verbose_name='Название категории')),
            ],
            options={
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена товара')),
                ('picture', models.ImageField(default='serveruploads/standard.png', upload_to='serveruploads', verbose_name='Картинка товара')),
                ('description', models.TextField(default='Дополнительное описание отсутствует', verbose_name='Описание товара')),
                ('goods_sold', models.IntegerField(default=0, verbose_name='Продано всего')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product_type', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
