# Generated by Django 5.0.1 on 2024-01-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='serveruploads/standard.jpg', upload_to='serveruploads', verbose_name='Картинка товара'),
        ),
    ]
